# Generated by Django 3.2.5 on 2021-07-19 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('locationName', models.TextField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('placeID', models.TextField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_trips', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=100)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='api.trip')),
            ],
        ),
        migrations.CreateModel(
            name='EventIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('locationName', models.TextField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('placeID', models.TextField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('suggestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tripSuggestedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventIdeas', to='api.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('locationName', models.TextField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('placeID', models.TextField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('alternativeTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='api.tripevent')),
            ],
        ),
    ]
