# Generated by Django 3.2.5 on 2021-07-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tripevent_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripevent',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
