# Generated by Django 3.2.5 on 2021-07-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tripevent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventidea',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
