# Generated by Django 3.2.5 on 2021-07-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210720_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripevent',
            name='locationName',
        ),
    ]
