# Generated by Django 3.2.5 on 2021-07-22 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_remove_tripevent_locationname'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='auth.user'),
            preserve_default=False,
        ),
    ]
