# Generated by Django 3.2.5 on 2021-07-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alternative_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
