# Generated by Django 3.2.5 on 2021-07-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210721_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventidea',
            name='status',
            field=models.CharField(choices=[('Suggested', 'Suggested'), ('Added', 'Added')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='locationName',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
