# Generated by Django 3.2.5 on 2021-07-22 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_eventidea_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripevent',
            name='eventIdea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tripEvent', to='api.eventidea'),
        ),
    ]
