# Generated by Django 3.2.5 on 2021-07-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tripevent_eventidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='status',
            field=models.CharField(choices=[('Suggested', 'Suggested'), ('Added', 'Added')], default='Suggested', max_length=100),
        ),
    ]
